replicaCount: 2

image:
  repository: traefik
  tag: "v3.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  annotations: {}

ingressRoute:
  dashboard:
    enabled: true

logs:
  general:
    level: INFO

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

ports:
  web:
    port: 8000
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    exposedPort: 443
    protocol: TCP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
