{{- if $.Values.secret.storeRef.name }}
{{- $globalRefreshInterval := $.Values.secret.refreshInterval }}
{{- range $ref := $.Values.secret.refs }}
{{- if $ref.remoteRef }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $ref.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "namespace.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $ref.refreshInterval | default $globalRefreshInterval }}
  secretStoreRef:
    name: {{ $.Values.secret.storeRef.name }}
    kind: ClusterSecretStore 
  target:
    name: {{ $ref.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $ref.remoteRef.key }}
{{- end }}
{{- end }}
{{- end }}
