apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.name }}
spec:
  provider:
    {{- if eq .Values.provider "vault" }}
    vault:
      server: {{ .Values.vault.server }}
      path: {{ .Values.vault.path }}
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.auth.mountPath }}
          {{- with .Values.vault.auth.role }}
          role: {{ . }}
          {{- end }}
          {{- with .Values.vault.auth.serviceAccountRef.name }}
          serviceAccountRef:
            name: {{ . }}
            namespace: {{ $.Values.vault.auth.serviceAccountRef.namespace }}
          {{- end }}
    {{- else if eq .Values.provider "azurekv" }}
    azurekv:
      vaultUrl: {{ .Values.azureKV.vaultUrl }}
      authType: {{ .Values.azureKV.authType }}
    {{- end }}
