apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ingress-controller
  labels:
    app: ingress-controller
    {{- include "ingress-controller.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ingress-controller
    {{- include "ingress-controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ .Values.ports.web.exposedPort }}
      targetPort: web
      {{- if .Values.service.nodePorts }}
      nodePort: {{ .Values.service.nodePorts.web }}
      {{- end }}
      protocol: TCP
    - name: websecure
      port: {{ .Values.ports.websecure.exposedPort }}
      targetPort: websecure
      {{- if .Values.service.nodePorts }}
      nodePort: {{ .Values.service.nodePorts.websecure }}
      {{- end }}
      protocol: TCP
