# Azure AKS - dev namespace

namespace:
  name: dev
  createResourceQuota: true
  resourceQuota:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 4Gi

apps:
  kotlin-spring:
    enabled: true
    configMapRefs:
      - name: kotlin-spring-configmap
    secretRefs:
      - name: db-secret
      - name: asb-secret
      - name: mongo-secret
    image:
      repository: ghcr.io/thanhleothanh/kotlin-spring
      tag: latest
      pullPolicy: Always
    replicaCount: 1
    service:
      port: 8080
    ingress:
      enabled: true
      hosts:
        - paths:
            - path: /kotlin-spring
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1024Mi

configMap:
  refs:
    - name: kotlin-spring-configmap
      data:
        ASB_QUEUE_MODE: asb
        ASB_QUEUE_NAME: demo-events

secret:
  storeRef:
    name: cluster-secret-store
  refreshInterval: 1m
  refs:
    - name: db-secret
      remoteRef:
        key: db-secret
    - name: mongo-secret
      remoteRef:
        key: mongo-secret
    - name: asb-secret
      remoteRef:
        key: asb-secret
