name: cluster-secret-store
provider: vault
vault:
  server: http://vault.vault:8200
  path: secret
  auth:
    mountPath: kubernetes
    role: cluster-secret-store-role
    serviceAccountRef:
      name: external-secrets
      namespace: external-secrets
