name: Deploy to Azure AKS

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Target namespace'
        required: true
        type: choice
        options:
          - dev
      resource_group:
        description: 'Azure resource group'
        required: true
        type: string
        default: 'rg-dev-web'
      cluster_name:
        description: 'AKS cluster name'
        required: true
        type: string
        default: 'personal-cluster'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # remember to Create Service Principal secret from az

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ github.event.inputs.resource_group }}
          cluster-name: ${{ github.event.inputs.cluster_name }}

      - name: Deploy namespace chart
        run: |
          helm upgrade --install ${{ github.event.inputs.env }}-apps ./charts/apps/namespace \
            -n ${{ github.event.inputs.env }} --create-namespace \
            -f ./environments/azure-aks/apps/${{ github.event.inputs.env }}/values.yaml \
            --set validations.verifyRefs=true \
            --wait \
            --atomic
